### PR TITLE
Add Chapter 6

### PR DESCRIPTION
**Pull request by jadeynryan**

### CODE REVIEW

**Review by jonthegeek — APPROVED** [review]
Looks good as long as the build works!

**Review by jonthegeek — CHANGES_REQUESTED** [review]
I don't know how to set up github with the python side of things yet (and I don't have it set up locally), but I know so far it has worked as long as you render everything and check it all in. Unfortunately I can't help past there, but someone in the book club channel might be able to help!

**Comment by jadeynryan** [comment]
Based on this github [issue](https://github.com/quarto-dev/quarto-actions/issues/11#issuecomment-1219447594), I changed freeze from auto to true in hopes that this build process won't re-render the whole book and honor the freeze.

**Review by jonthegeek — APPROVED** [review]
Good find! Thanks for the fix!

**Pull request merged**
