### PR TITLE
Notes for Chapter 5

### PR DESCRIPTION
**Pull request by DrEntropy**
Notes for reviewing Chapter 5, introduction to Pandas

### CODE REVIEW

**Review by jonthegeek — APPROVED** [review]
Looks good assuming it builds!

**Review by jonthegeek — CHANGES_REQUESTED** [review]
Hmm, it failed. I don't know anything about what it takes to get the Python to work, other than rendering it and uploading whatever gets produced. If you think you already did that... Ping Isabella, maybe?

**Comment by DrEntropy** [comment]
I will take a look at freezing the renders.  Thansk!

**Comment by DrEntropy** [comment]
I see that i  forgot to rerender after my final minor edit, try it now?

**Review by jonthegeek — DISMISSED** [review]
OK, hopefully this will do it!

**Comment by DrEntropy** [comment]
It still is not working so i did a full render (as per the instructions I realized after re-reading!)

**Review by jonthegeek — APPROVED** [review]
That did it, thanks!

**Pull request merged**
