### PR TITLE
Chapter 3 notes after R4DS session

### PR DESCRIPTION
**Pull request by opus1993**
a rendering of the whole book built with

- one added 03_notes.qmd page
- an added line in the _quarto.yml

### CODE REVIEW

**Review by jonthegeek — CHANGES_REQUESTED** [review]
I don't THINK we want yaml headers on the individual files. Does anything change if you remove the header on 03_notes.qmd? I guess if not it's fine to leave it, but partly I want to understand how things will work in here!

**Review by jonthegeek — CHANGES_REQUESTED** [review]
Oh, I also don't THINK we need the 03_notes_files/libs. We should add a rule to .gitignore (after deleting that and checking in the deletion) to ignore the *_notes_files dirs and see if it builds like I think it will. Oh, and maybe that's just there because of the header?

**Comment by opus1993** [comment]
> Oh, I also don't THINK we need the 03_notes_files/libs. We should add a rule to .gitignore (after deleting that and checking in the deletion) to ignore the *_notes_files dirs and see if it builds like I think it will. Oh, and maybe that's just there because of the header?

still investigating.  With the YAML header gone now, I'll try to delete manually and see what happens.

**Comment by opus1993** [comment]
> 

I attempted the deletion, and then re-render.  The 03_notes_files/libs folder re-appeared.  I will make an edit to .gitignore commit and push

**Review by jonthegeek — APPROVED** [review]
I un-ignored, deleted, and re-ignored so this PR didn't have that folder.... and the build still passed, so it looks good! Thanks!

**Pull request merged**
